### PR TITLE
Modernize repo and ship CJS and ESM modules

### PR DESCRIPTION
**Pull request by gamedevsam**
Things I've added in this PR:

- Bumped version to 1.0.0
- Added support for ESModule version of the package in addition to CommonJS
- Updated dependencies
- Added TypeScript types
- Prettier formatting (with format on save if you use vscode)
- Node based CLI to handle all package.json scripts (I like to write my build scripts with JavaScript)

Things I've removed:

- Angular (seems easy enough for users to add on their own, or they can stay in v0.6.0)
- Gulp & Bower

### CODE REVIEW

**Comment by gamedevsam** [comment]
@tomarad tests have been written and are passing. This is now ready for review, check it out and let me know what you think.

**Comment by tomarad** [comment]
Amazing! I'll take a look in the next couple of days and merge this.
Thanks @gamedevsam.

**Comment by gamedevsam** [comment]
Any concerns with this PR? I know there are a lot of opinionated changes here, feel free to give me feedback so we can get some form of this merged.

**Comment by tomarad** [comment]
> Any concerns with this PR? I know there are a lot of opinionated changes here, feel free to give me feedback so we can get some form of this merged.

Hey, I'm fine with most of the changes, besides moving from npm to pnpm. Do you mind undoing this change?
After that I'll test it a little bit more and merge.
Thanks!

**Comment by gamedevsam** [comment]
What's your issue with pnpm? It saves disk space on everyone's computers, and has faster install speeds than all other package managers. It's the obvious choice in 2023 and beyond for me.

**Comment by tomarad** [comment]
I understand.
Personally, I like using the default npm. I realize that it might be slower, and that it's opinionated, and that's my preference.
I can make the pnpm -> npm change myself if it's more comfortable for you.

Thanks again for this PR, it truly is amazing!

**Comment by gamedevsam** [comment]
Ok, no problem, it's your repo your rules, happy to compromise!

I still think pnpm is objectively better, but also am not an absolutist about it. Npm is plenty fast, just wasteful with disk space if you work with many repos.

**Comment by gamedevsam** [comment]
@tomarad I switched to npm.

**Comment by tomarad** [comment]
Thanks! I'll merge today or tomorrow.

**Comment by tomarad** [comment]
Published 1.0.0, thanks @gamedevsam.

**Comment by gamedevsam** [comment]
@tomarad can you make a release to npm soon? I'd like to update our team's package.json files to point once again to your package as opposed to my fork.

**Comment by tomarad** [comment]
> @tomarad can you make a release to npm soon? I'd like to update our team's package.json files to point once again to your package as opposed to my fork.

Can you check again? I published 1.0.0 to npm yesterday

**Comment by gamedevsam** [comment]
I see it now, sorry, I didn't see a tag on github so assumed it wasn't published already. Thanks for merging & publishing!

🥇

**Pull request merged**
